import { FC, ReactNode } from 'react';
import type { Metadata, Viewport } from 'next';

// Layout
import Layout from '@/components/Layout';

// Font
import { secondaryFont } from '@/public/fonts/fonts';

// CSS
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  themeColor: '#1F2937',
};

interface RootLayoutProps {
  children: ReactNode;
}

const RootLayout: FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body className={`body ${secondaryFont.className}`}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
};

export default RootLayout;
