import { FC, ReactNode } from 'react';
import type { Metadata } from 'next';

// CSS
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: ReactNode;
}

const RootLayout: FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body className="">{children}</body>
    </html>
  );
};

export default RootLayout;
